# Generated by Django 5.2 on 2025-04-10 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Preke',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pavadinimas', models.CharField(max_length=100)),
                ('aprasymas', models.TextField()),
                ('kaina', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kategorija', models.CharField(choices=[('ELE', 'Elektronika'), ('APR', 'Apranga'), ('MAI', 'Maistas'), ('KIT', 'Kita')], max_length=3)),
            ],
        ),
    ]
